export const HOME_URL = '/'
export const SIGNUP_URL = '/signup'
export const SIGNIN_URL = '/signin'
export const USER_URL = '/user'
export const USER_RESET_PASSWORD_URL = '/user/reset-password'
export const DASHBOARD_URL = '/dashboard'
export const DASHBOARD_CREATE_URL = '/dashboard/create'
