import { HandleError } from '@/lib/utils/error-handling/types'
import { AuthError } from 'next-auth'

/**
 * @function handleAuthError
 * @description Handles authentication-related errors generated by the NextAuth.js (Auth.js) library.
 * The function analyzes the type of `AuthError` and returns a standardized `HandleError` object,
 * which can be used for informing the user or for logging purposes.
 *
 * @param  error - The authentication error object received from NextAuth.js.
 * @returns  - A standardized error object including `type`, `message`, and `details`.
 */
export function handleAuthError(error: AuthError): HandleError {
  switch (error.type) {
    case 'CredentialsSignin':
      return {
        type: 'authenticate',
        message: 'Invalid credentials.',
        details: undefined,
      }
    default:
      return {
        type: 'authenticate',
        message: 'Something went wrong.',
        details: undefined,
      }
  }
}
